### PR TITLE
Reconcile dependencies between package.xml and CMakeLists.txt

### PR DESCRIPTION
**Pull request by nuclearsandwich**
These changes are informed by failures on the ROS builfdarm, specifically these builds:

* http://build.ros2.org/view/Cbin_uB64/job/Cbin_uB64__object_analytics_rviz__ubuntu_bionic_amd64__binary/2/console
* http://build.ros2.org/view/Cdev/job/Cdev__ros2_object_analytics__ubuntu_bionic_amd64/1/console

I haven't tested these changes locally and they may not actually reflect what you need. This is intended to be a starting point for the discussion.

Feel free to close this PR in favor of a separate solution.

### CODE REVIEW

**Comment by yechun1** [comment]
@nuclearsandwich thanks for your PR. 

I have a question about bloom-release process. Once we have code change, but not want to plus version. what others need we do?

Need we re-tag on the modified code on source?
Need we run bloom-release again to sync code to ros2_object_analytics-release?


1. need  need we 1. retag

**Comment by nuclearsandwich** [comment]
> I have a question about bloom-release process. Once we have code change, but not want to plus version. what others need we do?

With Git especially, if the source has changed, the version number should change. Git is designed to treat tags as immutable, if another individual pulls a tag, git will assume that tag can never change. It's possible to delete tags and create new ones with the same name, but git will not know that has happened. Bloom similarly expects code changes to come with a version bump and I would encourage you to make a patch release (for example from 0.5.0 to 0.5.1) as that's exactly what the patch numbers are intended for.

**Comment by yechun1** [comment]
@nuclearsandwich Yes, this is git project. Don't know how to make a patch release. Could I confirm with you if my understand is correct or not with your recommendation:
1. change code 
2. update the package version from 0.5.0 to 0.5.1(for example), new tag with 0.5.1.
3. run bloom release and submit PR to both rosdistro and -release.git

**Comment by nuclearsandwich** [comment]
Since this package has a changelogs. I would suggest adding

1. change code
2. update changelogs
3. update the package version from 0.5.0 to 0.5.1(for example), new tag with 0.5.1.
4. run bloom release which will update the release repository and open the PR to ros2/rosdistro

For steps 2 and 3, the package `catkin-pkg` has two helper utilities `catkin_generate_changelog` and `catkin_prepare_release` which can be used to automate the process of generating changelogs and updating package.xml versions. I use only catkin_generate_changelog, and I usually clean up the generated logs by hand before committing them.

One important thing to bear in mind is that every package in a repository needs to have the same version. So every package in this repository needs to move from 0.5.0 to 0.5.1.

**Comment by yechun1** [comment]
This should be standard steps, version/tag bump for any changes for stable releasing, We'll follow the process. Thanks very much.

**Comment by nuclearsandwich** [comment]
Glad to help. I forgot to mention that the ROS wiki article http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage has some more information about the release prep tools. There is a warning that says ROS 2's new build system presents some issues but catkin_generate_changelog at least does work. There are caveats using catkin_prepare_release with python packages in ROS 2 but that's not applicable for this repository.

**Comment by nuclearsandwich** [comment]
https://github.com/ros2-gbp/ros2_object_analytics-release/pull/1

> Not sure which steps missed on previous commit. Do you meet this issue before, and how you fix this?

I don't think we missed any steps when releasing the source repository. I checked the bloom `tracks.yaml` config file and found some changes that will make the described release process work. 

I made a change to the release repository in https://github.com/ros2-gbp/ros2_object_analytics-release/pull/1 which allows bloom to infer the new release version from the development branch. The PR body has an exact account of what changed and why.

Normally I wouldn't release a package for someone without getting their express permission beforehand. But since we're in different timezones and you to lose a whole day if my PR was incomplete I went ahead and merged it, then used it to release your 0.5.1. I've just merged that PR https://github.com/ros2/rosdistro/pull/377 so hopefully it works :crossed_fingers: 

If a 0.5.2 release is necessary, all you should need to do is follow the steps in https://github.com/intel/ros2_object_analytics/pull/54#issuecomment-444756484 and when running

```
bloom-release --rosdistro crystal --track crystal ros2_object_analytics
```

for step 4, the new bloom config should automatically detect and use the new version update.

**Comment by yechun1** [comment]
previous 0.5.0_crystal tagged with crystal branch, and 0.5.0 tagged with master. Sync master branch has latest code and is not ready for release, so we have create crystal branch and with 0.5.0_crystal branch. it is a little specific. The patch to upgrade version to 0.5.1 and use master branch will not work.  But I have changed crystal branch to master branch for bloom release, and tag code with 0.5.2 (removed _crystal), I think version bump mechanism most likely will work by bloom-release now.

**Comment by yechun1** [comment]
From [bloom tutorial - first time release](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Releasing_Your_Packages). 
I found `--edit `could also fix my previously issue, input configure each time while bloom release, especially for customized version and tag name. Needn't modify -release.git by manually. 

` bloom-release --rosdistro <ros_distro> --track <ros_distro> <your_repository_name> --edit`
This option will allow you to edit the track specified before making a release.

**Pull request merged**
